select * from province;

select row_to_json(province) from province;

select row_to_json(row(p_id,name)) 
from province  ;

with cte as (
    select  p_id , name from province where region = 'S'
)
select row_to_json(cte) from cte ;

copy (
    with cte as (
        select  p_id , name from province where region = 'S'
    )
select row_to_json(cte) from cte 
) to '/Users/kriengkrirat/Downloads/south.json'